# VOXEL PARAMETERS
VOXEL_SIZE: 0.05

# MAP NORMAL ESTIMATION PARAMETERS
NORMAL_FACTOR: 15

# MAP NORMAL ESTIMATION PARAMETERS
MAP_NORMAL_FACTOR: 15

# NOISE PARAMETERS----------------------------------------------------------------------------------

NOISE_MEAN: 0.0
NOISE_STD_DEV: 0.01
NOISE_PROBABILITY: 0.3

# FRAME-TO-FRAME PARAMETERS-------------------------------------------------------------------------

# FILTERING PARAMETERS
FTF_MAX_FRAMES_BETWEEN_KEYFRAMES: 3
FTF_FITNESS_THRESHOLD: 0.98
FTF_RMSE_THRESHOLD: 0.02
FTF_DISTANCE_THRESHOLD: 0.06
FTF_ANGLE_THRESHOLD: 1

# ICP PARAMETERS
FTF_CORRESPONDENCE_DISTANCE: 0.15

# KEY FRAME PARAMETERS------------------------------------------------------------------------------

# KEY FRAME SELECTION PARAMETERS
KF_DISTANCE_THRESHOLD: 0.10
KF_ANGLE_THRESHOLD: 3
MAP_NOVELTY_RATIO_THRESHOLD: 0.05

# ICP PARAMETERS
KF_CORRESPONDENCE_DISTANCE: 0.15

# ICP PARAMETERS
MAP_CORRESPONDENCE_DISTANCE: 0.1

KF_FUSION_CROP_SIZE_X_MIN: -5
KF_FUSION_CROP_SIZE_X_MAX: 5
KF_FUSION_CROP_SIZE_Y_MIN: -5
KF_FUSION_CROP_SIZE_Y_MAX: 5
KF_FUSION_CROP_SIZE_Z_MIN: -5
KF_FUSION_CROP_SIZE_Z_MAX: 5