
# VOXEL PARAMETERS
VOXEL_SIZE: 0.04

# ICP PARAMETERS
GENERAL_CORRESPONDANCE_DISTANCE: 0.5

# FEATURES ESTIMATION PARAMETERS
FEATURE_RADIUS: 0.15

# MAP NORMAL ESTIMATION PARAMETERS
NORMAL_FACTOR: 30

# MAP NORMAL ESTIMATION PARAMETERS
MAP_NORMAL_FACTOR: 20

# FRAME-TO-FRAME PARAMETERS-------------------------------------------------------------------------

# FILTERING PARAMETERS
FTF_MAX_FRAMES_BETWEEN_KEYFRAMES: 5
FTF_FITNESS_THRESHOLD: 0.95
FTF_RMSE_THRESHOLD: 0.015
FTF_DISTANCE_THRESHOLD: 0.1
FTF_ANGLE_THRESHOLD: 5

# ICP PARAMETERS
FTF_CORRESPONDENCE_DISTANCE: 0.2

# KEY FRAME PARAMETERS------------------------------------------------------------------------------

# KEY FRAME SELECTION PARAMETERS
KF_OVERLAP_RATIO_THRESHOLD: 0.875
KF_RMSE_THRESHOLD: 0.03
KF_DISTANCE_THRESHOLD: 0.3
KF_ANGLE_THRESHOLD: 15.0

# ICP PARAMETERS
KF_CORRESPONDENCE_DISTANCE: 0.15

# UTILS GENERAL PARAMETERS--------------------------------------------------------------------------  

# RESOLUTION LEVELS FOR MULTI-SCALE ICP
MULTI_VOXEL_RES_SIZES:
  - 0.16
  - 0.8
  - 0.04