
# VOXEL PARAMETERS
VOXEL_SIZE: 0.04

# ICP PARAMETERS
GENERAL_CORRESPONDANCE_DISTANCE: 0.5
FTF_CORRESPONDENCE_DISTANCE: 0.3

# FEATURES ESTIMATION PARAMETERS
FEATURE_RADIUS: 0.16

# NORMAL ESTIMATION PARAMETERS
NORMAL_FACTOR: 20

# KEY FRAME CANDIDATE PARAMETERS
FITNESS_THRESHOLD: 0.90
RMSE_THRESHOLD: 0.02
MAX_FRAMES_BETWEEN_KEYFRAMES: 5

# KEY FRAME SELECTION PARAMETERS
DISTANCE_THRESHOLD: 0.2
ANGLE_THRESHOLD: 15.0
OVERLAP_RATIO_THRESHOLD: 0.8

MULTI_VOXEL_RES_SIZES:
  - 0.15
  - 0.08
  - 0.02